### ISSUE TITLE
Data sets missing

### ISSUE THREAD

**Issue by amitsaha** [makeyourownneuralnetwork/makeyourownneuralnetwork#1]
Hi Tariq, in your notebooks,  you refer to the data sets as `mnist_train.csv` and `mnist_test.csv`, but the files in `mnist_dataset` are named differently, as they are subsets of the original data. Should the notebooks use the subset or the full CSV files should be downloaded?

**Comment by makeyourownneuralnetwork** [comment]
Hi Amit

yes - the datasets in github are subsets ... githib won't let me host
larger files.. the readme.txt and the book points people to the full files
on the web: http://pjreddie.com/projects/mnist-in-csv/

hope that helps!

**Comment by amitsaha** [comment]
Cool, thanks. Btw, I think https://git-lfs.github.com/ may be of help

**Comment by makeyourownneuralnetwork** [comment]
Thanks! I'll take a look .. I only use the web interface for github but may
start playing with the command line ... I havent done source control since
2003!
