### ISSUE TITLE
Error?

### ISSUE THREAD

**Issue by katyo456** [makeyourownneuralnetwork/makeyourownneuralnetwork#12]
Hi Tariq,
               I really like your book. Thanks.

Can you help me please? I'm new to Python and I get the following error when I try to run the code:

# load the mnist test data CSV file into a list
test_data_file = open("mnist_dataset/mnist_test_100.csv", 'r')
test_data_list = test_data_file.readlines()
test_data_file.close()
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
<ipython-input-26-96fbd31d119b> in <module>()
      1 # load the mnist test data CSV file into a list
----> 2 test_data_file = open("mnist_dataset/mnist_test_100.csv", 'r')
      3 test_data_list = test_data_file.readlines()
      4 test_data_file.close()

FileNotFoundError: [Errno 2] No such file or directory: 'mnist_dataset/mnist_test_100.csv'

Thank you,
Kate

**Comment by makeyourownneuralnetwork** [comment]
Hi @katyo456 ..this means the code is not finding the file. 

The usual reaons for this are (1) the file does not have the right name, or (2) it is in the wronf folder. 

Can you check that the file in the folder mnist_dataset/ is actually called mnist_test_100.csv

Get back to me if this doesn't help.
