### ISSUE TITLE
Weight initialize

### ISSUE THREAD

**Issue by anthony123** [makeyourownneuralnetwork/makeyourownneuralnetwork#14]
A More sophisticated weight initialization method is sample the weights from a normal probability distribution centered around zero and with a standard deviation that is related to the number of incoming links into a node. The implementation code is 

  `self.wih= numpy.random.normal(0.0, pow(self.hnodes, -.5), self.hnodes, self.inode))` 

However, I think the code should be 
`self.wih= numpy.random.normal(0.0, pow(self.inodes, -.5), self.hnodes, self.inode))` 

because self.inode is the incoming links.

Do I understand it correctly?

**Comment by makeyourownneuralnetwork** [comment]
I think you're right! good catch ... I'll look at this again with a fresh mind later and update the code and book.

Thanks @anthony123 !

**Comment by makeyourownneuralnetwork** [comment]
github notebooks have been updated - thanks @anthony123 

because this error isn't critical, as in it doesn't break the code or results in a big way, i'll wait until a few fixes have been collated before I update the print and ebooks
