### ISSUE TITLE
How to save result after training?

### ISSUE THREAD

**Issue by PhanDuc** [makeyourownneuralnetwork/makeyourownneuralnetwork#15]
Hi,

After training, I tried to save n (object of class neuralNetwork) with pickle but cannot reuse after saved!
Do you have any idea how to do reuse after training?

Many thanks for considering my request !

**Comment by makeyourownneuralnetwork** [comment]
you can save and load numpy arrays .. and in our case, the self.wih and self.who bumpy arrays are the ones which contain the learned state.

See here for examples:  

 - save bumpy array [https://docs.scipy.org/doc/numpy/reference/generated/numpy.save.html](https://docs.scipy.org/doc/numpy/reference/generated/numpy.save.html)
 - load numpy array [https://docs.scipy.org/doc/numpy/reference/generated/numpy.load.html](https://docs.scipy.org/doc/numpy/reference/generated/numpy.load.html)

I hope that helps .. maybe I should update the code to include load() and save() as additional functions for the neural network class?

**Comment by PhanDuc** [comment]
Thanks so much!
I think you should update save and load model.
Then teach us how to retrain model after load old model.
I hope what I have requested is possible.

**Comment by makeyourownneuralnetwork** [comment]
hi @PhanDuc - keep an eye out for a blog post on how to do this in the near future!

[http://makeyourownneuralnetwork.blogspot.co.uk](http://makeyourownneuralnetwork.blogspot.co.uk)
