### ISSUE TITLE
Integer v.s. float nit

### ISSUE THREAD

**Issue by LanceNorskog** [makeyourownneuralnetwork/makeyourownneuralnetwork#16]
Hi, 

Instead of running inside notebook, I typed in all the code to a straight Python file b/c I wanted to understand it all. 

I had to change makeyourownneuralnetwork/part2_neural_network_mnist_data.ipynb, line 237 from:
print ("performance = ", scorecard_array.sum() / scorecard_array.size)
to:
print ("performance = ", scorecard_array.sum() * 1.0 / scorecard_array.size)

I'm not a Python expert, I'm sure there's a more elegant way to do this. 

But, much more important, if the Notebook code does not need this coercion, this means that "Notebook Python" is subtly different from "CLI Python" !!

**Comment by LanceNorskog** [comment]
Oops, never mind, this is a P2 v.s. P3 issue. As I said, I'm not a Python expert :)

Love the book and your examples.

**Comment by makeyourownneuralnetwork** [comment]
thanks of raising it anyway! glad you found the answer
