### ISSUE TITLE
why differential (E/O) = -2 (T - O)

### ISSUE THREAD

**Issue by kocoten1992** [makeyourownneuralnetwork/makeyourownneuralnetwork#2]
Sorry, I can't find your email in the ebook, so if I can ask here :):

P/S: you know what, during asking this, I think I just solve the thing, but it much worth pointing out:

It a bit blurry on page 93 to the rest of the chapter, I'm working on it, on page 95:

```
Page 95, I will assume that:
(E/O)' = -2.(T - O) // but why?
```

I think I just solve it:
```
On some previous page, we do agree E function is (target - output)^2 or ( T - O )^2, so:

[ (T-O)^2 ] ' = [ T^2 -2.T.O + O^2 ] ' // and we differential by O, also T is a constant, so we will have

= 2.O - 2.T = -2.(T-O) // Am I correct?
```

But why you skip this, if this is a homework, then must have a link or the answer somewhere :-1:

**Comment by makeyourownneuralnetwork** [comment]
Hi - good question. Yes you are correct that 

E/O)' = -2.(T - O)

For many readers this is a very well known result from their studies at school. If however this result is not familiar, the book has a chapter at the back which introduces simple calculus and  you can see where this result comes from.

The more common way to arrive at the result is through the chain rule - also explained at the back of the book - but your method of expanding out the brackets also works. 

Here is an earlier draft of that chapter available for free online: [](http://makeyourownneuralnetwork.blogspot.co.uk/2016/01/a-gentle-introduction-to-calculus.html)
