### ISSUE TITLE
Kindle links

### ISSUE THREAD

**Issue by peralmered** [makeyourownneuralnetwork/makeyourownneuralnetwork#24]
I'm aware this is hardly the right place to post this issue, but I'm eager to get back to reading this great book:

I bought the Kindle version on Amazon, and the URL links on pages 132+133 (and possibly more?) don't work. Don't know if it's a limitation of the Kindle software or not, but regardless, a footnote with the verbatim URL wouldn't hurt.

Thanks for this book, I'm finally starting to have the pieces fall into place!

**Comment by makeyourownneuralnetwork** [comment]
thanks for flagging this - please contact me directly on makeyourownneuralnetwork at gmail dot com and we'll find a fix for you
