### ISSUE TITLE
Runtime warning for lambda function

### ISSUE THREAD

**Issue by Avinash-B** [makeyourownneuralnetwork/makeyourownneuralnetwork#25]
I am using the same code for constructing a neural network with 728 input neurons. This gives me a warning message saying that "overflow encountered in exp". BTW I am not using scipy library in my code.
![screenshot from 2018-01-24 09-18-14](https://user-images.githubusercontent.com/25326872/35313668-9c687eb4-00e7-11e8-9988-4f2c4874364d.png)
![screenshot from 2018-01-24 09-18-39](https://user-images.githubusercontent.com/25326872/35313669-9ce9b9c0-00e7-11e8-89f6-5d0a2293a67b.png)

Error in line 30

**Comment by makeyourownneuralnetwork** [comment]
you might be using the wrong function

the logistic function is expit(x) = 1/(1+exp(-x)) ... the brackets and negative sign are important

give that a go?

**Comment by Avinash-B** [comment]
Thank you Sir
