### ISSUE TITLE
unnecessary transpose code in the query function

### ISSUE THREAD

**Issue by steph-jung** [makeyourownneuralnetwork/makeyourownneuralnetwork#26]
in part2_neural_network.ipynb,

when
input_nodes = 1
hidden_nodes = 3
output_nodes = 1,

the code returns error since there's transpose code in
def query(self, inputs_list):
        # convert inputs list to 2d array
        inputs = numpy.array(inputs_list, ndmin=2).T  (<-----here)

**Comment by makeyourownneuralnetwork** [comment]
hi - whats the error you're getting?

are you using Python 3?

**Comment by Gerrit02** [comment]
Hello,
I do not understad the part:
inputs = numpy.array(inputs_list, ndmin=2).T

Will it automatically converted in a two dimensional 28x28 array.
But still you have also the label in the inputs_list?

**Comment by makeyourownneuralnetwork** [comment]
hi @Gerrit02  

That line converts from a python **list** to a numpy **array**. By default it will have dimensions (784,) with the second dimension undefined. By setting ndmin=2, it forces the dimensions to be (784,1) which avoids any problems later for example when using multiplication.

The data is never converted to a 28x28 array for the purposes of training or querying - there's no need. It is only done when the image is displayed in the other code examples.


Does that help?
