### ISSUE TITLE
How to run/execute the code?

### ISSUE THREAD

**Issue by Gerrit02** [makeyourownneuralnetwork/makeyourownneuralnetwork#28]
Hello,
I copy paste the code from github.com makeyourownneuralnetwork.
Then I select the run cell select below button.
Questions:

- how do I run the code at once in stead of Cell by Cell
- in every In Cell an asterix appears (in stead of number 1,2, ... etc...) see printscreen
- my last In command is print scorecard but every cell is executed without errors and still no output when executed my last cell

See printscreens below!
My question in general how do I have to run my code?
Tnx

[
![runningcode_01](https://user-images.githubusercontent.com/34437030/36448263-53d62254-1687-11e8-88a0-5776706fe7e4.JPG)
![runningcode_02](https://user-images.githubusercontent.com/34437030/36448264-53f8f5d6-1687-11e8-98ae-f35f54c6b2df.JPG)

](url)

**Comment by Gerrit02** [comment]
Hello,
I will try again when I at home. 
No I'm only succeeded to run Cell by Cell, I've got no errors however but no output neither.
How do you recognize the icon of the run all button?

**Comment by makeyourownneuralnetwork** [comment]
the run all you are looking for is  here ...
[https://datalab.noao.edu/docs/manual/_images/runallcells.png](https://datalab.noao.edu/docs/manual/_images/runallcells.png)

**Comment by Gerrit02** [comment]
Hello,
it works fine ;-) tnx. My performance was 0,97 but took more then 4 minutes on my pc.
Very nice book and very nice explained step by step.

Question: do you have a follow up or can you recommend now what to do next. Can you advice a book about deep learning or neural networks more in dept. Tnx...

**Comment by makeyourownneuralnetwork** [comment]
I would 3 things:

- join a meetup group on python and data science in your area - working with others is really fun and works well
- online courses like coursera, khan academcy are great
- a really solid textbook like Christopher Bishops are useful for reference eg http://www.springer.com/gb/book/9780387310732
