### ISSUE TITLE
General question

### ISSUE THREAD

**Issue by Gerrit02** [makeyourownneuralnetwork/makeyourownneuralnetwork#29]
Will the code also run when I should only make use of python (anaconda)? In stead of using Ipython?

**Comment by Gerrit02** [comment]
Hello, tried already by my own to run the code in python anaconda.
Allready two errors encountered, but don't know why... is there so much difference between python anaconda and ipython?

 File "C:/Users/gstevens/Desktop/MyPythonProjects/ProjectsAnaconda/LabelRecognition.py", line 15, in <module>
    class neuralNetwork:
  File "C:/Users/gstevens/Desktop/MyPythonProjects/ProjectsAnaconda/LabelRecognition.py", line 95, in neuralNetwork
    n = neuralNetwork(input_nodes, hidden_nodes, output_nodes, learning_rate)
NameError: name 'neuralNetwork' is not defined

**Comment by Gerrit02** [comment]
Hello I got it work on python anaconda.
Apparantly above was because of a typo or wrong indent.
However one remark: I must put the % matplotlib inline in comment.

Can you tell me why or in what do I have to replace this line of code?

![afbeelding](https://user-images.githubusercontent.com/34437030/36506026-a664ccfe-1755-11e8-8ef8-cbe2493d6089.png)

**Comment by makeyourownneuralnetwork** [comment]
most people use web based notebooks, in which case %matplotlib inline tells it to plot images/graphs in the web page and not in a separate window

if you're not plotting images or graphs you can leave it out

**Comment by Gerrit02** [comment]
What if you want to plot images/graphs using python anaconda?

**Comment by makeyourownneuralnetwork** [comment]
i dont know i'm not an expert i'm afraid
most people will use the web-version of anaconda python
