### ISSUE TITLE
Type Error

### ISSUE THREAD

**Issue by uriahshonor** [makeyourownneuralnetwork/makeyourownneuralnetwork#3]
I get error:

TypeError: Cannot cast array from dtype('float64') to dtype('S32) according to rule 'safe'

on the line:

hidden_inputs = numpy.dot(self.wih, inputs)

in method "query"

on training set:

mnist_train_100.csv

**Comment by makeyourownneuralnetwork** [comment]
sorry for the delay in getting back to you .. 

i just tested the code myself with a copy downloaded from github just now and i don't get the error

i can suggest some things that could be wrong ... your error suggests the inputs seem to have a string and not a number. 

also the method "query" for querying happens after training - did you get the error during traing or during querying?

I would check how you prepare your input - the code provided translates the "text" from the sampel datasets to floating point numbers using the numpy.asfarray() function.

`inputs = (numpy.asfarray(all_values[1:]) / 255.0 * 0.99) + 0.01
`
