### ISSUE TITLE
input fields ipython

### ISSUE THREAD

**Issue by Gerrit02** [makeyourownneuralnetwork/makeyourownneuralnetwork#30]
Hello,
what is the use of the avantage of the different inputfields in ipython. Why not put all the code in one input field? I wrote my code of the makeyourownneuralnetwork in one input field and it worked also.

**Comment by makeyourownneuralnetwork** [comment]
its best to look at a tutorial to the notebook to best answer your questions about python, input fields, inline and external graphcs, etcs

[1](https://ipython.org/ipython-doc/3/notebook/)
[2](http://cs231n.github.io/ipython-tutorial/)

**Comment by makeyourownneuralnetwork** [comment]
in brief the benefit us you can split up your code and re-run only the bits you want
