### ISSUE TITLE
Bias in input and hidden layers

### ISSUE THREAD

**Issue by Gerrit02** [makeyourownneuralnetwork/makeyourownneuralnetwork#36]
Hello Rashid,

I see you made a separate blog to describe and how to adapt your current code for how to save your network.

Is it possible to do the same for how to adapt and use your network with bias as well in input as hidden layer?

Thank you very much,

Gerrit

**Comment by makeyourownneuralnetwork** [comment]
here's the idea [http://makeyourownneuralnetwork.blogspot.co.uk/2016/06/bias-nodes-in-neural-networks.html](http://makeyourownneuralnetwork.blogspot.co.uk/2016/06/bias-nodes-in-neural-networks.html) but i haven't created any code for it

**Comment by Gerrit02** [comment]
Will you create any code of it? Like you did for saving a neural network? Also the idea is only talking for a bias in the input layer, not in the hidden layers. I'm wondering how far the code will be impacted if also the hidden layer(s) contains a bias.

Gerrit

**Comment by makeyourownneuralnetwork** [comment]
Hi - sadly I won't have time to write the code as I'm working on other projects. 

You can have a bias for the input layer and the middle hidden layer - which makes the network more general. In practice you experiment to find the minimum network for the problem you're trying to solve.
