### ISSUE TITLE
continue running 

### ISSUE THREAD

**Issue by Gerrit02** [makeyourownneuralnetwork/makeyourownneuralnetwork#39]
_If we come back to our training, we need to run the notebook up to the point just before training. That   means running the Python code that sets up the neural network class, and sets the various parameters like the number of input nodes, the data source filenames, etc.

We can then issue n.load() in a notebook cell to load the previously saved neural networks weights back into the neural network object n._

**Question**

How does the network known once loading the n.load() weights on which itteration step (meaning line in data set or epoch cycle) the training should continue?

In previous question I asked also how to save the weights from a fully trained network, but here too, how does the network known once the n.load() method has executed the network has been fully trained?

**Comment by makeyourownneuralnetwork** [comment]
The network doesn't know which data record it was interrupted on, or whether the network is fully trained.

You can write code to keep track if you want. Or you can just carry on training from the beginning. 

If the network is fully trained and you save the weights.. next time you just load the weights and use the network.
