### ISSUE TITLE
appended prepended

### ISSUE THREAD

**Issue by Gerrit02** [makeyourownneuralnetwork/makeyourownneuralnetwork#40]
In the query() and train() functions, the inputs_list has a 1.0 bias constant input prepended or appended to it.

What means prepended and appended

How do you have to code this?

**Comment by makeyourownneuralnetwork** [comment]
Prepend means add to the start, append means add to the end.

Sadly I don't have time to write this code as I'm working on other projects.

**Comment by Gerrit02** [comment]
Will you write a follow up of your book? More in dept details? Neural network with bias, saving, loading, etc...
Unsupervised learning? etc...

**Comment by makeyourownneuralnetwork** [comment]
Right now I am working on 2 other books (algorithmic art, text mining) - in future I might come back to neural networks.
