### ISSUE TITLE
(i)python for neural networks

### ISSUE THREAD

**Issue by Gerrit02** [makeyourownneuralnetwork/makeyourownneuralnetwork#41]
Hi Rashid,

can you recommend a book (i)python used to create a neural network?

**Comment by makeyourownneuralnetwork** [comment]
not sure what you mean by this question?

can I recommend a book on python or a book on neural networks?

for python I recommend online courses like khan academy and coursera

for neural networks - again online courses .. but also some deeper reference texts like Bishops book on machine learning

**Comment by Gerrit02** [comment]
Hi Rashid,
a book about neural networks created with Ipython or python.
A book that will be just go a litle bit deeper and more technical than your book...

Your sincerely,

**Comment by makeyourownneuralnetwork** [comment]
I'm afraid I don't know of any but I would recommend the online courses.
