### ISSUE TITLE
initialize the weights matrix

### ISSUE THREAD

**Issue by JustinNie** [makeyourownneuralnetwork/makeyourownneuralnetwork#44]
When initializing the weights matrix, the variance of matrix `wih` should be : `pow(self.hnodes, -0.5)`

same to the matrix `who`

**Comment by Gerrit02** [comment]
Hello JustingNie,
what is your point?
For wih it is: pow(self.inodes, -0.5)
for who it is: pow(self.hnodes, -0.5)

why should initialize the weights matrix the same for wih as for who?
(Dimension is different?)

**Comment by JustinNie** [comment]
Like me say in a picture way:
the code in your book is:
![img_2855014ef0be-1](https://user-images.githubusercontent.com/28496150/37137977-2ce9145e-22e3-11e8-992b-d59fb6a8547c.jpeg)
but the code in GitHub is:
<img width="770" alt="screen shot 2018-03-08 at 3 10 51 pm" src="https://user-images.githubusercontent.com/28496150/37137981-37902f14-22e3-11e8-9aca-546690e58715.png">
It is a little confusing!

**Comment by JustinNie** [comment]
Like me say in a picture way.
The code in your book is:
![img_2855014ef0be-1](https://user-images.githubusercontent.com/28496150/37138077-a3a29502-22e3-11e8-87f6-b1d3f8e6e5b8.jpeg)
But the code in GitHub is:
<img width="660" alt="screen shot 2018-03-08 at 3 14 52 pm" src="https://user-images.githubusercontent.com/28496150/37138089-ad32be80-22e3-11e8-8bf5-4fcf2c245bb8.png">
It's a little confusing!

**Comment by Gerrit02** [comment]
ok we let @makeyourownneuralnetwork answer that question. He is the author of the book :-)

**Comment by makeyourownneuralnetwork** [comment]
Hi @JustinNie - thanks for a great question.

The first thhing to say is that you can, in theory, initialise the weighst to any random number.

In practice however - we find that the if we limit our randomness to a smaller range the network learning can be faster.

A very common solution is to limit the random numbers to be between 0 and 1 .. or between -1 and +1.

A slightly more refined approach, which isn't absolutely necessary, is to pick the numbers from a normal distribution centred at 0.0 with a standard deviation which is the square root of the number of incoming links.  

What you you have spotted is an error in the early editions of the printed book. The correct code is in Github. The error in the book was corrected and all electronic ebooks can be updated for free if you ask amazon support. If you have any problems, get in touch with me at makeyourownneuralnetwork at gmail dot com and we'll fix it another way.

In the end the bug isn't major as it only affects the initial random values very slightly, they will already be in the right small range already.

**Comment by JustinNie** [comment]
OK, I see. 
Thank you very much.
