### ISSUE TITLE
own handwriting examples

### ISSUE THREAD

**Issue by Gerrit02** [makeyourownneuralnetwork/makeyourownneuralnetwork#45]
@makeyourownneuralnetwork 
I'm wondering, can you send the numbers you create your own via attach or via mail?
I'd like to experiment also with those.
It's a pritty that it is so hard to create 28x28 pixels images because of that low pixel rate.
A picture taken with a modern smartphone or camera is soon 1 Mbyte and more and if you want to convert to 28x28 the noise becomes really a lot.
Even if you do it eg with paint, you can define the area as 28x28 but that is so small area you can hardly drawn a number (see my last images) :-( a sent few post agoo.

**Comment by makeyourownneuralnetwork** [comment]
here is an example

i use a photo / image editing program to draw a number on a sqaure canvas of size eg 300 x 300

then i resize the image to 28x28 and save as PNG

![3_28x28](https://user-images.githubusercontent.com/17411198/37345431-d9612534-26c4-11e8-92b2-5597b331d98b.png)

There are more examples in the github repo here:
https://github.com/makeyourownneuralnetwork/makeyourownneuralnetwork/tree/master/my_own_images

**Comment by Gerrit02** [comment]
What I do not understand is if you draw it in 300x300 and afterwards you save it to 28x28 you don't have noise on the drawing? 
Which photo/image editing program do you use?

**Comment by makeyourownneuralnetwork** [comment]
I have used pinta, gimp and affinity photo

noise should be ok as long as there isn't too much - the point of neural networks is that they are tolerant to some noise

**Comment by Gerrit02** [comment]
When I draw a number in let's say 300x300 and then convert to 28x28 I have a lot of noise and my number is really misformed. I did it with paint.

**Comment by makeyourownalgorithmicart** [comment]
please attach the 300x300 and the 28x28 image
