### ISSUE TITLE
Making the the neural Network MPI enabled

### ISSUE THREAD

**Issue by DJN1** [makeyourownneuralnetwork/makeyourownneuralnetwork#50]
Hello, I just recently got access to a HPC where I can get large amounts of resources for programs. Recently the HPC started to implement Jupyter-notebooks. Considering that training these neural nets can be quite resource-heavy, how can I make the code work with Message Passing Interface(MPI)?

**Comment by makeyourownneuralnetwork** [comment]
Hi @DJN1 - great question.

There are a few things to think about here.

1. The MPI interface is fairly low level and today there are nicer higher-level or even transparent mechanisms for distributed computing. I would look at something like **dask** for Python / Numpy which distributes computation and is part of the python data science ecosystem.

2. We have to ask ourselves what algorithm we're using. Do we want to spread a weight matrix over many nodes? Do we want to train many networks on separate nodes, and somehow combine the weight updates? Do we do this in batches? Do we update all nodes with a single weight change?

Regarding (2) the questions are of current academic interest and different people are investigating different ideas. I'm not an expert but a Google search will give you rich avenues to explore.
