### ISSUE TITLE
saving weight

### ISSUE THREAD

**Issue by mohi-sh** [makeyourownneuralnetwork/makeyourownneuralnetwork#51]
hi 
thanks for writting this sweat book,
i want to save the final weight of the neural network ,wih and who, but i am new to python and ai can you help me how to do this.
i try to save the weight but got some numbers but they does not make sense even.

**Comment by makeyourownneuralnetwork** [comment]
Hi - I wrote a blog about saving and reloading the weights.

[http://makeyourownneuralnetwork.blogspot.com/2018/02/saving-and-loading-neural-networks.html](http://makeyourownneuralnetwork.blogspot.com/2018/02/saving-and-loading-neural-networks.html)

I hope that helps - if not, do get back to me.

**Comment by mohi-sh** [comment]
thanks for your response.
it woked.
i also run this flow following code to save they weighs in text file cause
i could not find a software to open .npy files (i mean real visiualization)
:
def save(self):
      numpy.savetxt('saved_wih.txt', self.wih)
      numpy.savetxt('saved_who.txt', self.wih)
thank again :)

**Comment by makeyourownneuralnetwork** [comment]
great solution!
