### ISSUE TITLE
ValueError: shapes (200,784) and (342,1) not aligned: 784 (dim 1) != 342 (dim 0)

### ISSUE THREAD

**Issue by Lurrobert** [makeyourownneuralnetwork/makeyourownneuralnetwork#52]
`# test the neural network

# scorecard for how well the network performs, initially empty
scorecard = []

# go through all the records in the test data set
for record in test_data_list:
    # split the record by the ',' commas
    all_values = record.split(',')
    # correct answer is first value
    correct_label = int(all_values[0])
    # scale and shift the inputs
    inputs = (numpy.asfarray(all_values[1:]) / 255.0 * 0.99) + 0.01
    # query the network
    outputs = n.query(inputs)
    # the index of the highest value corresponds to the label
    label = numpy.argmax(outputs)
    # append correct or incorrect to list
    if (label == correct_label):
        # network's answer matches correct answer, add 1 to scorecard
        scorecard.append(1)
    else:
        # network's answer doesn't match correct answer, add 0 to scorecard
        scorecard.append(0)
        pass
    
    pass`
After writing code on test set it says:
`ValueError: shapes (200,784) and (342,1) not aligned: 784 (dim 1) != 342 (dim 0)`
Can you help fix it?

**Comment by makeyourownneuralnetwork** [comment]
can you tell us which line the error points to?

normally this error means your test data is not of the right shape - the input images need to be 28x28 = 784 .. 

your data seems to have a size of 342

**Comment by Lurrobert** [comment]
Sure
outputs = n.query(inputs)
and this refers to 
def query(self, inputs_lists):
        
        inputs = np.array(inputs_lists, ndmin=2).T
        #print(inputs.shape)
        # calculate signals into hidden layer
         hidden_inputs = np.dot(self.w_i_h, inputs) ---- this line give error

**Comment by makeyourownneuralnetwork** [comment]
yes this confirms that your inputs are not of the correct size

input images must be 28x28 pixels, unrolled to 784 values which are fed to the networks as `inputs`

to make this work you need to resize your images, either by using an image editing app or using a script or code.
