### ISSUE TITLE
don't understand the principle of backquery 

### ISSUE THREAD

**Issue by ZoroSpace** [makeyourownneuralnetwork/makeyourownneuralnetwork#54]
```

1. def backquery(self, targets_list):
2.         # transpose the targets list to a vertical array
3.         final_outputs = numpy.array(targets_list, ndmin=2).T
4.         
5.         # calculate the signal into the final output layer
6.         final_inputs = self.inverse_activation_function(final_outputs)
7. 
8.         # calculate the signal out of the hidden layer
9.         hidden_outputs = numpy.dot(self.who.T, final_inputs)
10.         # scale them back to 0.01 to .99
11.         hidden_outputs -= numpy.min(hidden_outputs)
12.         hidden_outputs /= numpy.max(hidden_outputs)
13.         hidden_outputs *= 0.98
14.         hidden_outputs += 0.01
15.         
16.         # calculate the signal into the hidden layer
17.         hidden_inputs = self.inverse_activation_function(hidden_outputs)
18.         
19.         # calculate the signal out of the input layer
20.         inputs = numpy.dot(self.wih.T, hidden_inputs)
21.         # scale them back to 0.01 to .99
22.         inputs -= numpy.min(inputs)
23.         inputs /= numpy.max(inputs)
24.         inputs *= 0.98
25.         inputs += 0.01
26.         
27.         return inputs

```
why can we calculate the hidden_outputs by numpy.dot(self.who.T, final_inputs), in line 9?
why can we calculate the inputs by numpy.dot(self.wih.T, hidden_inputs), in line 20?

as we know, who\*hidden_outputs = final_inputs, and wih\*inputs = hidden_inputs, but line 9 and line 20 are not like this. why can we do that?

**Comment by makeyourownneuralnetwork** [comment]
Great question1

When you say "as we know, who*hidden_outputs = final_inputs, and wih*inputs = hidden_inputs" - this relates to the signal going forward in the network from input to output.

What the **backquery** is trying to do is follow the signal as if it started at the outputs and flow towards the inputs. This means the equations for **feedforward** don't apply. What we do is apply the same principles to work out what he equations mights be for **backwards** flow .. which is what we talk abut in the book. For example, splitting the signal equally amongst the hidden nodes, but weighted by the link weights .. `numpy.dot(self.who.T, final_inputs)`.

Get back to me if this doesn't help.

**Comment by ZoroSpace** [comment]
Of course it helps, and thanks a lot! The steps of the backquery is very clear, thank you
