### ISSUE TITLE
I don't seem to track the value error

### ISSUE THREAD

**Issue by wcares** [makeyourownneuralnetwork/makeyourownneuralnetwork#57]
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-1-01f00c21ed1d> in <module>
    114         # all_values[0] is the target label for this record
    115         targets[int(all_values[0])] = 0.99
--> 116         n.train(inputs, targets)
    117         pass
    118     pass

<ipython-input-1-01f00c21ed1d> in train(self, inputs_list, targets_list)
     41 
     42         # calculate signals into hidden layer
---> 43         hidden_inputs = numpy.dot(self.wih, inputs)
     44         # calculate the signals emerging from hidden layer
     45         hidden_outputs = self.activation_function(hidden_inputs)

ValueError: shapes (200,784) and (0,1) not aligned: 784 (dim 1) != 0 (dim 0)

I am using your book and I am stuck with this error and helpless. 
First I typed all the codes with understanding and when I saw this error then copy and paste it but again
causing the same problem.
I have used code from here( https://github.com/makeyourownneuralnetwork/makeyourownneuralnetwork/blob/master/part2_neural_network_mnist_data.ipynb )
Could you suggest what is causing this error? Please help.....

**Comment by makeyourownneuralnetwork** [comment]
Hi @wcares 

Your `inputs` array seems to be of size (0,1) which is wrong. it should be (784,1)

This suggests an error somewhere in your code where the `inputs` is created from the trainign data

I just now downloaded the code and CSV data again to check and it works fine for me.

Are you copying the code by hand? Have you tried downloading the notebook itself, or copying and pasting the python code from there?

<img width="1102" alt="screenshot 2018-12-18 at 03 21 20" src="https://user-images.githubusercontent.com/17411198/50131183-e7cfd800-0278-11e9-9b84-7b8276451671.png">

**Comment by wcares** [comment]
I copy the codes from here ( https://github.com/makeyourownneuralnetwork/makeyourownneuralnetwork/blob/master/part2_neural_network_mnist_data.ipynb ) to test it. It's not working on me .

**Comment by makeyourownneuralnetwork** [comment]
can you print out an `inputs` just before line 43 so we can see what it is?

**Comment by makeyourownneuralnetwork** [comment]
also which version of python are you using?

**Comment by wcares** [comment]
it's 3.6 version.

**Comment by wcares** [comment]
This is the hole code I am using in spyder(python 3.6 version) with mnist data files .

import numpy

# scipy.special for the sigmoid function expit()
import scipy.special

#library for plotting arrays
import matplotlib.pyplot


# Neural network class definition
class neuralNetwork:
    #Initialize the neural network
    def __init__(self, inputnodes, hiddennodes, outputnodes, learningrate):
        #set number of nodes in each input, hidden, output layer
        self.inodes = inputnodes
        self.hnodes = hiddennodes
        self.onodes = outputnodes

        #link weight matrices, wih and who
        #weights inside that arrays are w_i_j, where link is from node i to node j in the next layer
        #w11 w21
        #w12 w22 etc
        self.wih = numpy.random.normal(0.0, pow(self.hnodes, -0.5),(self.hnodes,
                                                                    self.inodes))
        self.who = numpy.random.normal(0.0, pow(self.onodes, -0.5),(self.onodes,
                                                                    self.hnodes))
        #learning rate
        self.lr = learningrate

        #activation function is the sigmoid function
        self.activation_function = lambda x:scipy.special.expit(x)
                                       
        pass

    #train the neural network
    def train(self, inputs_list, targets_list):
        #convert inputs list to 2d array
        inputs = numpy.array(inputs_list, ndmin=2).T
        targets = numpy.array(targets_list, ndmin=2).T

        # calculate signals into hidden layer
        hidden_inputs = numpy.dot(self.wih, inputs)

        # calculate the signals emerging from hidden layer
        hidden_outputs = self.activation_function(hidden_inputs)

        #calculate signals into final output layer
        final_inputs = numpy.dot(self.who, hidden_outputs)

        #calculate the signals emerging from final output layer
        final_outputs = self.activation_function(final_inputs)
        
        # output layer error is the (target - actual)
        output_errors = targets - final_outputs
        
        #hidden layer error is the output_errors, split by weights, recombined
        # at hidden nodes
        hidden_errors = numpy.dot(self.who.T, output_errors)
        
        # update the weight for the links between the hidden and output
        #layers
        self.who += self.lr * numpy.dot((hidden_errors * hidden_outputs *(1.0 - final_outputs)),
                                        numpy.transpose(hidden_outputs))
        
        # update the weights for the links between the input and hidden layers
        self.wih += self.lr*numpy.dot((hidden_errors*hidden_outputs *(1.0 -
                            hidden_outputs)), numpy.transpose(inputs))                       
        

        pass

    #query the neural network
    def query(self, inputs_list):
        #convert input list to 2d array
        inputs = numpy.array(inputs_list, ndmin=2).T

        # calculate signals into hidden layer
        hidden_inputs = numpy.dot(self.wih, inputs)

        #calculate the signals emerging from hidden layer
        hidden_outputs = self.activation_function(hidden_inputs)

        #calculate signals into final output layer
        final_inputs = numpy.dot(self.who, hidden_outputs)

        # calculate the signals emerging from final output layer
        final_outputs = self.activation_function(final_inputs)

        return final_outputs
    
        

# number of input, hidden and output nodes
input_nodes = 784
hidden_nodes = 200
output_nodes = 10

# learining rate is 0.3
learning_rate = 0.1

# create instance of neural network
n = neuralNetwork(input_nodes, hidden_nodes, output_nodes, learning_rate)

#load the mnist training data CSV file into a list
training_data_file = open("d:/documents/useful documents/mnist data/mnist_train_100.csv", "r")
training_data_list = training_data_file.readline()
training_data_file.close()

#train the neural network


#go through all records in the training data set
for record in training_data_list:
    #split the record by the ',' commas
    all_values = record.split(',')
    
    # scale and shift the inputs
    inputs = (numpy.asfarray(all_values[1:])/ 255.0 * 0.99) + 0.01
    
    #create the target output values(all 0.01, except the desired label which 0.99
    targets = numpy.zeros(output_nodes) + 0.01
    
    #all_values[0] is the target label for this record
    targets[int(all_values[0])] = 0.99
    n.train(inputs, targets)
    pass

#load the mnist test data CSV file into a list
test_data_file = open("d:/documents/useful documents/mnist data/mnist_test_10.csv", "r")
test_data_list = test_data_file.readlines()
test_data_file.close()



# test the neural network

# scorecard for how well the network performs, initially empty
scorecard = []

# go through all the records in the test data set
for record in test_data_list:
    # split the record by the ',' commas
    all_values = record.split(',')
    # correct answer is first value
    correct_label = int(all_values[0])
    # scale and shift the inputs
    inputs = (numpy.asfarray(all_values[1:]) / 255.0 * 0.99) + 0.01
    # query the network
    outputs = n.query(inputs)
    # the index of the highest value corresponds to the label
    label = numpy.argmax(outputs)
    # append correct or incorrect to list
    if (label == correct_label):
        # network's answer matches correct answer, add 1 to scorecard
        scorecard.append(1)
    else:
        # network's answer doesn't match correct answer, add 0 to scorecard
        scorecard.append(0)
        pass
    
    pass

# calculate the performance score, the fraction of correct answers
scorecard_array = numpy.asarray(scorecard)
print ("performance = ", scorecard_array.sum() / scorecard_array.size)

    

![screenshot 1](https://user-images.githubusercontent.com/45957151/50133505-f8ea0a80-02b3-11e9-8fc0-56e1ac3228be.png)

I hope this could help you find the reason of this error. Thanks..

**Comment by wcares** [comment]
Sorry(novice to python)  I don't understand which input should I  print. Is it csv file which I rescaled and shifted or else ?

**Comment by makeyourownneuralnetwork** [comment]
in your train function, add a print:

```
def train(self, inputs_list, targets_list):
    #convert inputs list to 2d array
    print(inputs)
    inputs = numpy.array(inputs_list, ndmin=2).T
```

you might want to change the train loop to only call train() once otherwise you'll get a lot of output

```
# go through all records in the training data set
    for record in training_data_list[:1]:
````

also check the training data file contains the right data, you might want to open it in a text edit or use head/less from the command line

```
head mnist_dataset/mnist_train.csv
```

let me know what you find

**Comment by wcares** [comment]
Thanks, problem solved for now but not in the way you told but yeah there was problem in inputs. So I just divide part by part each code and figured it out.

Problem was in these lines of code and when I modify this then inputs pop out. So appreciate your help and thank you very much...
training_data_file = open("mnist_dataset/mnist_train_100.csv", 'r')  //( When I changed this whole section then it worked)
training_data_list = training_data_file.readlines()
training_data_file.close()

**Comment by makeyourownneuralnetwork** [comment]
@wcares that's great!

was it an isssue with Windows path name?

**Comment by wcares** [comment]
No , windows path name was correct and as I said earlier, I started checking each line of code to print inputs or values before inputs. So each code worked fine but only these three lines causing problem although directory path was correct. So I just delete this whole section and write code with different names but same path and worked.

**Comment by wcares** [comment]
(I haven't completed the whole book yet but this one question popped out in my head and hope you don't mind)
Like us, when we learn from something and we learn it completely then we don't need that data and we can recognize that stuff. I mean, I have trained this network and it means it doesn't need that training data which I linked  the training data. So, how could this neural network learned something new if it still needs that training data file. It could have worked without that data if it's trained. But not. Why?

**Comment by wcares** [comment]
hello @makeyourownneuralnetwork 
Isn't there a way to only test neural network once it trained? Because every time, it's taking much more time to run through training data and after that it tests testing data. I mean train once with large data sets and test this neural network many times without training next time. Please consider about this and above  question .

**Comment by benj01** [comment]
@wcares - Sure, after training the network you can save the weights and than use it happily ever after without training. You also don’t need to test it again and again.
The process is:
1) Train the Network
2) Test the Network to see if the training worked (well enough)
3) Use the Network to make predictions on new examples (also called query the Network or inference)

**Comment by wcares** [comment]
Thanks to you a lot @makeyourownneuralnetwork now I can save neural network weights.
But still I have some problems. I don't see any thing wrong with this image but still says no match when I query these photos. Please could you check what is going on with this images. Please help!

https://drive.google.com/file/d/16sZ77jgYyZQiJodr6DSPR7d0Qz6EgOxj/view?usp=sharing
https://drive.google.com/file/d/1XzoTmPrqkPqFf-HlH3zX12rrYW1063wx/view?usp=sharing
https://drive.google.com/file/d/1MffHTNPiFV9MT2dsvsFW03iOxE3GlXE6/view?usp=sharing
https://drive.google.com/file/d/1gqYjALP6ASbwrIyLU4U9CgM7t5-qd5RF/view?usp=sharing

**Comment by makeyourownneuralnetwork** [comment]
@wcares - if you trained with the MNIST training set then these images are not always going to be correctly identified because they are mostly off-centre compared to the MNIST ones. 

you'll get better results if you normalise for size and centre the numbers.

of course if you want a neural network that can deal with this then you need a training set that contains such images (60, 000 of them!) and probably a deeper network to account for the translational variance. 

i hope that helps explain the reason these images are not succeeding.

**Comment by wcares** [comment]
Ok thanks and much appreciated for helping through all my questions....

**Comment by makeyourownneuralnetwork** [comment]
no problem! 

ps - If you really like the book, please do add an amazon review. It helps me invest time in my next book.

**Comment by wcares** [comment]
Yeah Sure..
Wait! is there any new Book? When it will release ? or that is follow up of this book or other different area scope?

**Comment by makeyourownneuralnetwork** [comment]
hey @wcares 

It will be on text mining .. here's the blog that goes with it that shows what i'm working on .. 
[http://intuitivetextmining.blogspot.com/](http://intuitivetextmining.blogspot.com/)

release probably early-mid 2019

I also have a book out on Algorithmic Art which you can find on Amazon.
