### ISSUE TITLE
Why do you use (target - ouput)^2 and not the quadratic error?

### ISSUE THREAD

**Issue by Ditox123** [makeyourownneuralnetwork/makeyourownneuralnetwork#58]
I was wondering why you use this error instead of the quadratic error 1/2*(target - ouput)^2?

Moreover, when defining targets, why put the matrix in 2 dimensions (784,1) instead of taking a vector of only one dimension (784). Is this to avoid problems with matrix multiplication?

Oh, and by the way, I find your program very clear :)

**Comment by makeyourownneuralnetwork** [comment]
hi @Ditox123 thanks for the great questions!

I found that Python had trouble with matrix multiplication if the second dimension of the matrix wasn't explicitly set .. even if it was set to 1. The numpy library doesn't have a concept of a 1-d vector in the sense you suggest. 

I'm not sure I understand your question about the error. Do you mean why is it not (target-output) and why have chosen to square it (target-output)^2 ?

Here is an early blog I wrote trying to explore this.. most of it is wrong .. the answer is at the bottom of the blog in the "update".
[http://makeyourownneuralnetwork.blogspot.com/2016/01/why-squared-error-cost-function.html](http://makeyourownneuralnetwork.blogspot.com/2016/01/why-squared-error-cost-function.html)

If that doesn't help - get back to me.
