### ISSUE TITLE
Hidden Nodes Doubt

### ISSUE THREAD

**Issue by ServerProcessor** [makeyourownneuralnetwork/makeyourownneuralnetwork#6]
Hi,
Thanks for the material. Why are the Hidden Nodes take as 200 ?

**Comment by makeyourownneuralnetwork** [comment]
You can choose any number but you need to find the best number for your
task.

Too few and there aren't enough to learn the relationship between the input
and output.

Too many and it takes too long to keen the right relationship.

So I need real world cases, you have to experiment.


Hope that helps.


Tariq

**Comment by ServerProcessor** [comment]
Works well, Thanks!
