### ISSUE TITLE
Different code to the book

### ISSUE THREAD

**Issue by agrigo2s** [makeyourownneuralnetwork/makeyourownneuralnetwork#60]
Hi,
your Code here says in "In [3]:", line 16 and 17:
        self.wih = numpy.random.normal(0.0, pow(self.inodes, -0.5), (self.hnodes, self.inodes))
        self.who = numpy.random.normal(0.0, pow(self.hnodes, -0.5), (self.onodes, self.hnodes))
but your book says:
        self.wih = numpy.random.normal(0.0, pow(self.hnodes, -0.5), (self.hnodes, self.inodes))
        self.who = numpy.random.normal(0.0, pow(self.onodes, -0.5), (self.onodes, self.hnodes))
Regards,
Artur

**Comment by makeyourownneuralnetwork** [comment]
Hi @agrigo2s 

Earlier versions of the book had this error. The code on github is correct. 

If you have the ebook you can ask Amazon for a free update to latest version.

If you have the print book, email me at makeyourownneuralnetwork at gmail dot com and I'll send you an updated version as a PDF.
