### ISSUE TITLE
I don't understand the derivation of the error!

### ISSUE THREAD

**Issue by Ditox123** [makeyourownneuralnetwork/makeyourownneuralnetwork#61]
In your book you say, that the derivation of a squared function like (tk-ok)² corresponds to -2(tk-ok), why isn't it 2(tk-ok)?

**Comment by couchexpert** [comment]
Hi,
you can convert the term (tk-ok)^2 into tk^2 - 2*tk*ok + ok^2

The derivation of this term to ok is:
-2*tk + 2*ok = -2 * (tk - ok)

Hope that helps.
Regards
Rolf

**Comment by makeyourownneuralnetwork** [comment]
yes - @couchexpert  is correct

many students learn the chain-rule which also gives the same result...
  d/dx (A-Bx)^2
= 2(A-Bx) * d/dx (A-Bx)
= 2(A-Bx) * -B
= -2B(A-Bx)

( you can set B=1 to get -2(A-x) which is not 2(A-x)

---

another way to remember this is that the derivative of (tk-ok)^2 is not the same as (tk+ok)^2
