### ISSUE TITLE
Issue with the backquary

### ISSUE THREAD

**Issue by doorteeth** [makeyourownneuralnetwork/makeyourownneuralnetwork#63]
def backquary(self, targets_list):
        final_outs = np.array(target_list, ndmin=2).T
        final_inputs = self.inverse_function(final_outs)
        hidden_outputs = np.dot(self.who.T, final_inputs)
I think this hidden_outputs  equation doesn't hold.
final_inputs = np.dot(self.who, hidden_outputs) are similar to 
A = B * C.
hidden_outputs = np.dot(self.who.T, final_inputs) are similar to 
C = B.T * A.
The two equations combine to get 
A = B * B.T * A
B * B.T = E 
This is wrong.

**Comment by LiuZ0814** [comment]
I am confused too now

**Comment by makeyourownneuralnetwork** [comment]
sorry for late reply ... my maths is a little rusty but B*B.T isn't the identity unless very specific conditions apply?
