### ISSUE TITLE
bias neurones

### ISSUE THREAD

**Issue by 221V** [makeyourownneuralnetwork/makeyourownneuralnetwork#67]
hello!
i read http://makeyourownneuralnetwork.blogspot.com/2016/06/bias-nodes-in-neural-networks.html but do not understand how to add bias neurones into code(

can you make example code with bias?
thanks

**Comment by makeyourownneuralnetwork** [comment]
this guide includes simple code (using only numpy)  and includes code to show how bias nodes can be implemented - I hope this helps.

https://towardsdatascience.com/lets-code-a-neural-network-in-plain-numpy-ae7e74410795

(apologies or the late reply)
