### ISSUE TITLE
Code not working

### ISSUE THREAD

**Issue by ServerProcessor** [makeyourownneuralnetwork/makeyourownneuralnetwork#7]
https://github.com/makeyourownneuralnetwork/makeyourownneuralnetwork/blob/master/part3_load_own_images.ipynb

This is regarding the above file.

On line In [75], the code gives an error "TypeError: Image data can not convert to float". Please help me get through this error.

**Comment by makeyourownneuralnetwork** [comment]
Hi - I have just tested this with a fresh install of the GitHub software and sample image files, and the latest python 3.6 from Anaconda.

It seems to work ok for me.

Googling that error suggest the images might not be there or are of the wrong format. 

Do you have images in the right folder, in the format described in https://github.com/makeyourownneuralnetwork/makeyourownneuralnetwork/blob/master/my_own_images/readme.txt ?

**Comment by makeyourownneuralnetwork** [comment]
also are you sure you are using python 3.x not 2.x?

**Comment by camx** [comment]
Are you referring to this line?

matplotlib.pyplot.imshow(our_own_dataset[3][1:].reshape(28,28),
cmap='Greys', interpolation='None')

**Comment by makeyourownneuralnetwork** [comment]
@ServerProcessor  is this issue now resolved ? or do you need help with it?
cc @camx

**Comment by ServerProcessor** [comment]
Sorry for updating late. Its resolved. Thank you!
