### ISSUE TITLE
XOR problem

### ISSUE THREAD

**Issue by szymekTS** [makeyourownneuralnetwork/makeyourownneuralnetwork#70]
I just wanted to try simple version of neural network "part2_neural_network". So i try to solve xor problem with my code:
[My Code](https://github.com/szymekTS/NeuralNetwork/blob/master/NN.ipynb)
What I have done wrong ?

**Comment by makeyourownneuralnetwork** [comment]
it looks like it works?

**Comment by szymekTS** [comment]
I changed Network configuration. With 2 input, 2 hidden, and 1 output, i get results like 1, 0.5, 0.5, where it should be 1, 1, 0,0
I workaround with Network configuration 2,4,1. It work
