### ISSUE TITLE
error comes up

### ISSUE THREAD

**Issue by ANZ161** [makeyourownneuralnetwork/makeyourownneuralnetwork#73]
after executing the following code:
epochs = 5

for e in range(epochs):
    # go through all records in the training data set
    for record in training_data_list:
        # split the record by the ',' commas
        all_values = record.split(',')
        # scale and shift the inputs
        inputs = (numpy.asfarray(all_values[1:]) / 255.0 * 0.99) + 0.01
        # create the target output values (all 0.01, except the desired label which is 0.99)
        targets = numpy.zeros(output_nodes) + 0.01
        # all_values[0] is the target label for this record
        targets[int(all_values[0])] = 0.99
        n.train(inputs, targets)
        pass
    pass

This error comes up:
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-20-8ce378d7980f> in <module>
     11         targets = numpy.zeros(output_nodes) + 0.01
     12         # all_values[0] is the target label for this record
---> 13         targets[int(all_values[0])] = 0.99
     14         n.train(inputs, targets)
     15         pass

IndexError: index 5 is out of bounds for axis 0 with size 3

**Comment by avinaashdhumal** [comment]
Hey! @ANZ161  I just checked your code and it works well.

**Comment by thomascp** [comment]
Hi,
You can check output_nodes value.

**Comment by makeyourownneuralnetwork** [comment]
apologies for the late reply to this one, I'll close it assuming it is fixed, but get back to me if it isn't

to debug; trying printing one all_values to see if the data was actually parsed properly
