### ISSUE TITLE
Use this NN codes to classify the animals is not working

### ISSUE THREAD

**Issue by thomascp** [makeyourownneuralnetwork/makeyourownneuralnetwork#74]
Hi @makeyourownneuralnetwork ,

I am a newbie in the area of the neural network. After reading your great introduction book, I changed a little to make the 'class neural network' a more common one, it becomes easy for me to add layers and nodes in each hidden layer.
See https://github.com/thomascp/neural_network_python/blob/master/neural_network.py

I used more than 3 layers(eg. 4-7) and more nodes in each hidden layer (eg. `700*400*200*100`), but it doesn't work well.

And also I used this model to try to classify different animals (for example, cats, dogs, pandas), it doesn't work well also even with more layers and more nodes in each layer.
I googled, and it is said CNN is good at classifying the different animals, but nobody gives a good explanation about why the normal NN doesn't work well. Could you give me some advice or tell me how to google it in the right way?
Any advice would be appreciated! Thanks!

BR,
Peng

**Comment by makeyourownneuralnetwork** [comment]
Hi @thomascp 

Yes, CNNs will be better suited for broader image classification. 

Google has a very good short introduction:  https://developers.google.com/machine-learning/practica/image-classification/convolutional-neural-networks

My next book also explains image classification with CNNs with sample working code too: https://www.amazon.com/dp/B085RNKXPD

--

Large neural networks are harder to train and so the aim is to try to find the minimal size that will do the job. The CNN architecture really helps by enabling network to zoom into each area of an image to extract features with which to decide on classification.
