### ISSUE TITLE
No such file or directory error

### ISSUE THREAD

**Issue by AGUPTA050403** [makeyourownneuralnetwork/makeyourownneuralnetwork#75]
I am on page 147 from the make your own neural network book and have saved the csv files as well as the ipython files in a folder, with the csv files in a folder called mnist_datatset within that folder. 

However when I run the code 
data_file= open("mnist_dataset/mnist_train_100.csv", 'r')
data_list= data_file.readlines()
data_file.close()

I get the following error:
FileNotFoundError: [Errno 2] No such file or directory: 'mnist_dataset/mnist_train_100.csv'

Where am I going wrong?

**Comment by makeyourownneuralnetwork** [comment]
hi, is the mnist_dataset folder in the same place as your python folder?

you can test this by running a command in a notebook cell to see where you are:

`!pwd`

and list the contents

`!ls`
