### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by grace1018** [makeyourownneuralnetwork/makeyourownneuralnetwork#76]
``# plot image
matplotlib.pyplot.imshow(our_own_dataset[item][1:].reshape(28,28), cmap='Greys', interpolation='None')

# correct answer is first value
correct_label = our_own_dataset[item][0]
# data is remaining values
inputs = our_own_dataset[item][1:]

**Comment by makeyourownneuralnetwork** [comment]
hi @grace1018 I'm not sure I understand the question or problem. Would you be able to explain again?

**Comment by grace1018** [comment]
sorry，I repeat again; when run this code,the error was list out of range
`runfile('E:/python/data_sort/png_neuralNetwork.py', wdir='E:/python/data_sort')
Traceback (most recent call last):

  File "E:\python\data_sort\png_neuralNetwork.py", line 108, in <module>
    matplotlib.pyplot.imshow(our_own_dataset[item][1:].reshape(28,28), cmap='Greys', interpolation='None')

IndexError: list index out of range`
the code lines below:
`item = 5

# plot image
matplotlib.pyplot.imshow(our_own_dataset[item][1:].reshape(28,28), cmap='Greys', interpolation='None')

# correct answer is first value
correct_label = our_own_dataset[item][0]
# data is remaining values
inputs = our_own_dataset[item][1:]`

**Comment by makeyourownneuralnetwork** [comment]
try item=0 to make sure the data is actually loaded
if it is, then perhaps the folder doesn't contain several images, only one?

**Comment by grace1018** [comment]
> try item=0 to make sure the data is actually loaded
> if it is, then perhaps the folder doesn't contain several images, only one?

I set item=0,but still list out of range,
I user 2images,6&8.png
![image](https://user-images.githubusercontent.com/67529931/86872819-a9766400-c10f-11ea-8753-89c69e5bffd6.png)

**Comment by grace1018** [comment]
> try item=0 to make sure the data is actually loaded
> if it is, then perhaps the folder doesn't contain several images, only one?

I rename the image,then code can run normally,but still bugs,I have try to review,thank u for your reply

**Comment by makeyourownneuralnetwork** [comment]
ok - let me know if you need more help.

**Comment by grace1018** [comment]
> ok - let me know if you need more help.

thank u for reply,the code has run normally without bugs,thanks
